// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fztxvrnyljbevnkrfjjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6dHh2cm55bGpiZXZua3JmamprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMjY0OTEsImV4cCI6MjA2NTcwMjQ5MX0.pl5fg-ujY6xIGt5EKBwKV0UIvZm41gX1lu2Ak9HaPQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);